import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'
import Footer from '@/components/Footer';
import Input from '@/components/Input';
import Button from '@/components/Button';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Home() {

  let router = useRouter();

  const [filmes, setFilmes] = useState();

  useEffect(() => {
    axios.get("http://localhost:1337/api/filmes?populate=*")
      .then((res) => setFilmes(res.data.data))
      .catch((error) => console.log(error))
  }, [])

  console.log(filmes)

  return (
    <>
      <Head>
        <title>Minhas Séries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <section className={styles.containerSearch}>
          <div className={styles.containerTitleButton}>
            <div className={styles.containerTitle}>
              <h1>Bem vindo (a)</h1>
              <h2>Explore suas séries favoritas</h2>
            </div>
            <div className={styles.containerButton}>
              <Input type="text" placeholder="Faça uma pesquisa" />
              <Button>Buscar</Button>
            </div>
          </div>
        </section>

        <section className={styles.cardListFilme}>
          {filmes?.map((filme) => (
            <div key={filme.id} className={styles.containerCardFilme}>
              <p>{filme.attributes.titulo}</p>
              <Link href={`/filme/${filme.id}`}>
                <img src={"http://localhost:1337" + filme.attributes.imagem_capa.data.attributes.url} />
              </Link>
            </div>
          ))}
        </section>
      </main>
      <Footer />
    </>
  )
}
